#pragma once

using namespace ATL;

template <class T>
class CProxy_ISciterEvents : public IConnectionPointImpl<T, &__uuidof(_ISciterEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
